trigger:
- main 

resources:
- repo: self


stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:  
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: camunda-artifact'
      inputs:
        ArtifactName: 'camunda-artifact'

    - task: Docker@0
      displayName: 'Build an image'
      inputs:
        azureSubscription: 'FILLED IN AZURE DEVOPS'
        azureContainerRegistry: 'FILLED IN AZURE DEVOPS'
        action: Build an image
        imageName: $(Build.Repository.Name)-$(Build.SourceBranchName)
        
    - task: Docker@0
      displayName: 'Push an image'
      inputs:
        azureSubscription: 'FILLED IN AZURE DEVOPS'
        azureContainerRegistry: 'FILLED IN AZURE DEVOPS'
        action: Push an image
        imageName: $(Build.Repository.Name)-$(Build.SourceBranchName)
