# This is the default application settings
# Change this information as soon as possible
# You can see more examples in the readme file

spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: demo
  password: demo